In [9]:
import pandas as pd
import numpy as np
import sklearn.model_selection as ms
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

df = pd.read_excel("SubjectsClassification.xlsx",'Sentiments_Analysis')
df

Sentence Class
0           the course was very good  Good
1                    it was bery bad   Bad
2                        It was nice  Good
3                      seems perfect  Good
4                            Not bad   Bad
5   needs improvement on the content   Bad
6             Content was impressive  Good
7                     You are stupid   Bad
8                  Never, I will not   Bad
9                     Excellent dear  Good
10                             Good   Good
11                               Bad   Bad
12                              Nice  Good
13                             Never   Bad

In [10]:
df['Class'] = df['Class'].map({'Good':0, 'Bad':1})

In [11]:
x = df.Sentence
y = df.Class

In [13]:
x_train, x_test, y_train, y_test = ms.train_test_split(x, y, test_size = 0.4, random_state = 1)

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [17]:
xx = vect.fit_transform(["Hi How are you How are you doing", "Hi what's up", "Wow that's awsome", "CS602"])

In [19]:
vect.get_feature_names()

['are',
 'awsome',
 'cs602',
 'doing',
 'hi',
 'how',
 'that',
 'up',
 'what',
 'wow',
 'you']

In [21]:
print(xx.toarray())

[[2 0 0 1 1 2 0 0 0 0 2]
 [0 0 0 0 1 0 0 1 1 0 0]
 [0 1 0 0 0 0 1 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 0]]


In [34]:
x_train_vect = vect.fit_transform(x_train)

In [35]:
x_test_vect = vect.transform(x_test)

In [36]:
mnb = MultinomialNB()
mnb.fit(x_train_vect, y_train)
y_pred = mnb.predict(x_test_vect)
accuracy_score(y_pred, y_test)

0.6666666666666666

In [40]:
x_tr = vect.transform(["This was a very good match"])
yy = mnb.predict(x_tr)
print(yy)
x_tr = vect.transform(["This was a very bad match"])
yy = mnb.predict(x_tr)
print(yy)

[0]
[1]
